app/app.go, cmd/planetmint-god/cmd/root.go, config/config.go, go.mod, go.sum, x/machine/keeper/issue_response.go, x/machine/keeper/msg_server_attest_machine.go
added OSC response listener with logging
added Machine NFT issuance for each machine attestation process
added CID and Planetmint Issuer extPublicKey to the issuance process
=> Improve communication to liquid issuance service

.github/workflows/release.yaml
=> [ci] Add release pipeline

app/app.go, app/app_test.go
// See https://github.com/rddl-network/issues/issues/33
=> Rename addresses from cosmos* to plmnt*

config/config.go, x/dao/abci.go
add config for issuance endpoint and port and trigger in dao/abci.go
=> 2 trigger token reissuance on liquid including the distribution

docs/static/openapi.yml, tests/e2e/machine/suite.go, x/machine/keeper/msg_server_attest_machine.go
removes validations that have been moved to the AnteHandler
=> remove duplicate validation

.github/workflows/audit.yaml, config.yml
- [ci] Check generated files
- [ignite] Fix multiple main packages found
=> Small fixes/improvements

app/ante/check_reissuance_decorator.go, app/simulation_test.go, util/issue_commands.go, x/dao/abci.go, x/dao/keeper/msg_server_reissue_rddl_proposal.go, x/machine/keeper/msg_server_attest_machine.go
=> Replace fmt.PrintX calls by proper logging

.github/workflows/audit.yaml, .golangci.yaml
* Move setup into config file
* Add forbidigo to default linters
=> [ci] Add forbidigo to golangci-lint

.golangci.yaml, util/determine_block_proposer.go, util/elementsd_connector.go, util/issue_commands.go, util/validate_signature.go, x/asset/keeper/asset.go, x/asset/keeper/msg_server_test.go, x/dao/abci.go, x/dao/keeper/msg_server_reissue_rddl_proposal.go, x/dao/keeper/reissuance.go, x/dao/util.go, x/machine/keeper/msg_server_attest_machine.go, x/machine/keeper/trust_anchor.go
Golang uses:
- Camel Case for variable names, e.g. `firstName`
- Camel Case for private function names, e.g. `getFirstName`
- Pascal Case for public function names, e.g. `GetFirstName`
=> [ci] Add nosnakecase to golangci-lint

cmd/planetmint-god/cmd/root.go
a hotfix to enable the automated config-root-dir configuration
=> using GetConfig() to utilize the singleton

tests/e2e/machine/suite.go
adds a e2e test case where a machine attestation fee is granted by a different address so that the machine does not need to be funded first
=> add machine allowance e2e test

config/config.go
fixed the config parsing issue
=> Fix liuqid notarization - 3rd 

lib/tx.go, util/issue_commands.go, x/dao/abci.go, x/dao/keeper/msg_server_distribution_request.go, x/dao/keeper/msg_server_reissue_rddl_proposal.go, x/machine/keeper/msg_server_attest_machine.go
* fixed configuration bug in lib/tx
* improved method declarations and error handling for the util/issue_command.go methods
* improved logging for the application layer and the function calls
=> Improving rpc command issuance

go.mod, go.sum, util/elementsd_connector.go
=> Use elements RPC library

go.mod, go.sum, testutil/network/network.go
=> [test] Use elements RPC mock server

tests/e2e/dao/suite.go, util/rddl_token_test.go, x/dao/keeper/distribution_test.go, x/dao/keeper/reissuance.go, x/dao/keeper/reissuance_test.go
Adjusted to the peer-reviewed re-issuance values
=> adjusted re-issuance values and the corresponding test cases.

config/config.go, go.mod, go.sum, util/mqtt.go, util/mqtt_test.go, x/dao/keeper/msg_server_init_pop.go
* added MQTT lib
* added MQTT config params: domain, port user, password
* sending PoPInit commands to devices par of the pop (after delivery of the PoPInit message)
* Added test case to verify the working of the MQTT connection (test is skipped and designed for manual tests (lack of credentials))
=> Initializing the PoP process on the tasmota nodes

.github/workflows/audit.yaml
Execute jobs in parallel to speed up the workflow.
=> refactor: github audit workflow

app/ante/check_reissuance_decorator.go, util/issue_commands.go, util/logger.go, util/mqtt.go, x/dao/keeper/msg_server_distribution_request.go, x/dao/keeper/msg_server_reissue_rddl_proposal.go, x/dao/keeper/reissuance.go, x/machine/keeper/msg_server_attest_machine.go
- Introduce logger tags
- Log variable contents
- Fix testing logger to support string formatting
=> refactor: improve logging

app/ante/ante.go, app/ante/expected_keepers.go, app/ante/gaskv_cost_decorator.go, app/app.go, tests/e2e/dao/cli_test.go, tests/e2e/dao/gas_consumption_suite.go
gas kv decorator checks if tx signer is validator operator and sets gaskv store consumption to 0 if so
=> Add gaskv ante decorator

tests/e2e/dao/asset_distribution_suite.go, tests/e2e/dao/cli_test.go
=> test: add e2e test for asset distribution

util/mqtt.go
Removed 2nd init() method that caused behaviour during testing and real execution
=> Fixed MQTT auth issues  (indeterministic behaviour)

util/mqtt.go
fixed decision-making bug within SendMqttPopInitMessagesToServer from last release
=> Fixed MQTT sending message bug

testutil/keeper/machine.go, x/machine/genesis.go, x/machine/keeper/params.go, x/machine/keeper/params_test.go, x/machine/keeper/query_params_test.go, x/machine/types/keys.go, x/machine/types/params.go
added missing param definitions (default)
=> * added default params for x/machine/params

config/config.go, tests/e2e/dao/asset_distribution_suite.go, tests/e2e/dao/pop_participant_selection_suite.go, tests/e2e/dao/suite.go, x/dao/keeper/params.go, x/dao/types/params.go, x/machine/keeper/params.go
This partially reverts commit b1c4d11ccf3e98bd46a13d7fb54b6b5c0aefbf29.
=> Revert "Revert unnecessary config patch (#323)"

config/config.go, tests/e2e/dao/asset_distribution_suite.go, tests/e2e/dao/pop_participant_selection_suite.go, tests/e2e/dao/suite.go, x/dao/keeper/params.go, x/dao/types/params.go, x/machine/keeper/params.go
This reverts commit b205c5ff29df25bad6b923bae327b88bdad89518.
This needs to be removed so that the parameters are read from chain.
=> Revert "Revert "Revert unnecessary config patch (#323)" (#324)"

util/machine_nft_test.go, util/mqtt.go, x/machine/keeper/msg_server_attest_machine.go
PoP execution does not work as expected. 
Bug identified: wrong string composition.
=> fixed mqtt URI bug

.golangci.yaml, lib/tests/e2e/cli_test.go, lib/tests/e2e/suite.go, lib/tx.go, tests/e2e/asset/cli_test.go, tests/e2e/asset/suite.go, tests/e2e/dao/asset_distribution_suite.go, tests/e2e/dao/cli_test.go, tests/e2e/dao/gas_consumption_suite.go, tests/e2e/dao/pop_participant_selection_suite.go, tests/e2e/dao/restricted_msgs_suite.go, tests/e2e/dao/suite.go, tests/e2e/machine/cli_test.go, tests/e2e/machine/suite.go, util/issue_commands.go, util/machine_nft_test.go, util/sync.go, x/machine/keeper/msg_server_attest_machine.go
=> added TermintionWaitGroup

testutil/network/network.go
=> stageing network takedown to avoid leveldb panics

.github/workflows/audit.yaml
// https://stackoverflow.com/a/68746128
=> test: run action dynamically for each module in a repository

config/config.go, monitor/mqtt_monitor.go, util/mqtt.go
* added configuration value mqtt-tls (bool) to support tls and non-tls connections (testing)
* added TSL support for mqtt
=> TLS support for planetmint

clients/claim_client.go, config/config.go
- lazyLoad rddl-claim-service-client
- fix default value for claim-host in config
=> Fix rddl claim client load

monitor/mqtt_monitor.go, monitor/mqtt_monitor_test.go
add only legit machine addresses to the PoPSelection process
=> add only legit machine addresses to the PoPSelection process

clients/shamir_coordinator_client.go, config/config.go
- add certs path for mtls client
=> feat: add certs path and mtls setup for shamir coordinator client

config/config.go
this is handled by shamir coordinator now.
=> chore: remove obsolete rpc config

x/machine/keeper/query_get_machine_by_address.go, x/machine/keeper/query_get_machine_by_address_test.go, x/machine/keeper/query_get_machine_by_public_key.go, x/machine/keeper/query_get_machine_by_public_key_test.go, x/machine/keeper/query_get_trust_anchor_status.go, x/machine/keeper/query_get_trust_anchor_status_test.go
update error messages on machine queries
=> 427 add more details to machine not found error message

app/ante/check_machine_decorator.go, app/ante/check_validator_decorator.go, app/ante/deduct_fee_decorator.go, app/ante/setup_context_decorator.go, monitor/mqtt_monitor.go, util/logger.go, x/dao/keeper/challenge.go, x/dao/keeper/challenge_test.go, x/dao/keeper/distribution_test.go, x/dao/keeper/msg_server_init_pop.go, x/dao/keeper/msg_server_reissue_rddl_proposal.go, x/dao/keeper/msg_server_report_pop_result.go
add additional test to verify that validatorPopReward is calculated in correct magnitude
=> test: add additonal validatorPopReward reallocation test

config/config.go, lib/config.go, lib/tx.go, monitor/mqtt_monitor.go, monitor/mqtt_monitor_test.go, testutil/network/network.go, util/issue_commands.go, util/machine_nft_test.go, util/mqtt.go
- add setter and getter vor ValidatorAddress
- getter checks if TrustWallet is connected and retrieves address from TW
=> 447 add validatoraddress getter to config

tests/e2e/dao/pop/selection_suite.go, x/dao/keeper/msg_server_distribution_result.go
- refactor claim resolving
- add step to check for unresolved past claims
- update pop test suite to account for past unresolved claims
=> feat: add unresolved claim cleanup

.golangci.yaml, tests/e2e/dao/pop/selection_suite.go, x/dao/keeper/msg_server_distribution_result.go, x/dao/keeper/msg_server_init_pop.go, x/dao/keeper/msg_server_report_pop_result.go
- challenge initiator rewards are now issued on InitPoP
- refactor claim conversion so that only challenger and challengee get stale rewards converted
- adjust test case because number of InitPoPs leaves to different result on distribution result
=> 461 validator earn rewards for sending pop init successfully

app/app.go, monitor/backend.go, monitor/interface.go, monitor/mqtt_monitor.go, x/dao/keeper/keeper.go
=> feat(mqtt): start monitor after api server

util/rddl_token_test.go, x/dao/keeper/msg_server_distribution_result.go
* clear unresolved claims for the initiators as well
=> clear unresolved stagged claims for pop initiators

Makefile, contrib/devtools/Makefile
sources:
* https://github.com/cosmos/cosmos-sdk/blob/v0.47.14/Makefile
* https://github.com/cosmos/cosmos-sdk/blob/v0.47.14/contrib/devtools/Makefile
closes #483
=> chore(sims): copy makefiles from cosmos-sdk
