planetmint/planetmint-go

cmd/planetmint-god/cmd/root.go
config/config.dev.json
config/config.go
config/config.prod.json
go.mod
go.sum
x/machine/keeper/msg_server_attest_machine.go

This patch extends `app.toml` and adds the following section with these default values:
```
[planetmint]
watchmen-endpoint = "localhost"
watchmen-port = 7401
```
A global singleton `plmntConfig` is introduced to save and access the values similar to how cosmos does it (see
vendor/github.com/cosmos/cosmos-sdk/types/config.go).
Different environments can be managed by changing the values in `app.toml` and restarting the daemon.
// Closes #53

[config] Add planetmint section to `app.toml`

---

config/params.go
testutil/keeper/asset.go
testutil/sample/sample.go
x/machine/keeper/msg_server_attest_machine.go

Up to know we just use the Bitcoin mainnet parameters `chaincfg.MainNetParams` for Liquid. That's okay, because we use them for creating and verifying extended private and public keys. Those only depend on `HDPrivateKeyID` and `HDPublicKeyID`, which are the same for Bitcoin and Liquid networks.
The only real difference is the `HDCoinType` used for key derivation, which we want to use in the future. So it is a good idea to introduce this value now.

Introduce Liquid network parameters

---

.github/workflows/audit.yaml

Error:
* module requires Go 1.20

[ci] golangci-lint action needs Go 1.20

---

config/config.go
util/issue_commands.go

This partially reverts commit 1927c4d47219c428e4d12cfd9015f0137af7a030.
// Closes #142

Use globally defined keyring backend from client.toml

---

util/issue_commands.go

Otherwise the chain stop, because the call to the Tendermint RPC does not return.

[util] Make `buildSignBroadcastTx()` non-blocking

---

.github/workflows/audit.yaml

Version v28.0.0 was released and breaks the pipeline.

[ci] Pin ignite version to v0.27.1

---

x/machine/keeper/msg_server_attest_machine.go

* Removed error throwing within the AttestMachine method
* Added more extensive logging around that call

fixed error throwing bug that lead to block creation inconsistencies

---

x/dao/keeper/distribution.go
x/dao/keeper/distribution_test.go

the previous code didn't add precision to the values. thus, the value for the distribution tx was invalid.

fixed precsion issue within the distribution order

---

tests/e2e/asset/suite.go
tests/e2e/dao/suite.go
tests/e2e/machine/suite.go
testutil/cli/cmd.go

Just a small improvement to not forget to check the error code of the transaction and not only from the command itself.

[test] Check `TxResponse` on every `ExecTestCLICmd()`

---

x/machine/keeper/msg_server_attest_machine.go

`k.isNFTCreationRequest(msg.Machine)` was removed as it became obsolete and we are not issuing generic tokens from within the machine attestation process.
Closes #242

fix: remove check from machine attestation request

---

util/logger.go

From this:
```
ERR [app] reissue: failed. valid result: %v proposer: %s validator
identity: %s module=server
```
to this:
```
ERR [app] reissue: failed. valid result: true proposer:
9d3b2072f96f9481de983700605fbcd9158d5b63 validator identity:
31615187759d4bdb1c43ea7e7b9be91066042fbf module=server
```

fix: app logger formatting

---

app/ante/check_reissuance_decorator.go
app/ante/expected_keepers.go
config/config.go
tests/e2e/dao/suite.go
x/dao/abci.go
x/dao/keeper/msg_server_distribution_request.go
x/dao/keeper/query_reissuances_test.go
x/dao/keeper/reissuance.go
x/dao/keeper/reissuance_test.go

Reissue and reissuance are standalone words and should not contain an uppercase `I` in the variable name. This should only happen to connect different word like: file name gets `fileName` resp. `FileName`.

refactor: fix casing for reissuance variable

---

config/config.go
tests/e2e/dao/pop_participant_selection_suite.go
util/issue_commands.go
util/mocks/mqtt.go
util/mqtt.go
util/mqtt_test.go
x/dao/abci.go
x/dao/keeper/keeper.go
x/dao/keeper/msg_server_init_pop.go
x/dao/keeper/msg_server_report_pop_result.go

* simplified and improved logging
* added MQTT-based availability check for PoP participants
* extended MQTT mocking
* Only the block proposer will send out the MQTT messages to the pop participants
* Added a configuration value for the MQTT response timeout

Verifying the availability of PoP participants

---

tests/e2e/dao/suite.go

reinstate test by setting crddl assertions to the expected amounts after handling a distribution result

test: fix crddl assertion on pop result e2e test

---

testutil/network/loader.go
testutil/network/network.go

moved initialization code to network initialization so that potential DLT failures during the first 7 blocks won't appear.

tidy up ci logs

---

.github/workflows/audit.yaml
.github/workflows/release.yaml
.github/workflows/sonar.yaml

Warning:
```
Node.js 16 actions are deprecated. Please update the following actions
to use Node.js 20: actions/checkout@v3, actions/setup-go@v4.
```

fix: deprecated github actions

---

lib/config.go
lib/tests/e2e/suite.go
lib/tx.go
lib/utils.go
tests/e2e/asset/suite.go
tests/e2e/dao/basic/suite.go
tests/e2e/dao/distribution/asset_distribution_suite.go
tests/e2e/dao/gas/gas_consumption_suite.go
tests/e2e/dao/msgs/restricted_msgs_suite.go
tests/e2e/dao/pop/selection_suite.go
tests/e2e/machine/suite.go
testutil/network/network.go
util/logger.go

* made lib.config.Config attributed private and protected write operations via Mutex
* network.network.cleanup takes down the nodes in reverse order now
* moved the TerminationWaitGroup.Wait call to the cleanup method after validator termination and before the file removal is executed
* added TestingLogger mutex to avoid accidental data races

added more sync objects to avoid accidential data races

---

x/asset/keeper/asset.go
x/asset/keeper/asset_test.go

returning only one CID on the asset/address call to avoid tasmota crashes

hot fix for the tasmota PoP issues

---

tests/e2e/asset/suite.go
tests/e2e/dao/basic/suite.go
tests/e2e/dao/distribution/asset_distribution_suite.go
tests/e2e/dao/pop/selection_suite.go
tests/e2e/machine/suite.go
x/asset/client/cli/query.go
x/asset/client/cli/query_address.go
x/asset/client/cli/query_cid.go
x/asset/client/cli/query_params.go
x/dao/client/cli/query.go
x/dao/client/cli/query_challenge.go
x/dao/client/cli/query_challenges.go
x/dao/client/cli/query_distribution.go
x/dao/client/cli/query_mint_requests.go
x/dao/client/cli/query_params.go
x/dao/client/cli/query_redeem_claim.go
x/dao/client/cli/query_reissuance.go
x/dao/client/cli/query_reissuances.go
x/machine/client/cli/query.go
x/machine/client/cli/query_activated_trust_anchor_count.go
x/machine/client/cli/query_active_trust_anchor_count.go
x/machine/client/cli/query_address.go
x/machine/client/cli/query_liquid_assets.go
x/machine/client/cli/query_params.go
x/machine/client/cli/query_public_key.go
x/machine/client/cli/query_trust_anchor.go

- use one `cmd.AddCommand(...)`
- sort commands
- use `GetCmd...` function name style

refactor(query): align with cosmos-sdk style

---

monitor/backend.go
monitor/interface.go
monitor/mqtt_monitor.go

also directly return values instead of assigning them first.

refactor(mqtt): defer unlock where applicable

---

x/dao/keeper/msg_server_test.go

added test case to cover and identify cases Distribution result caused crashes. e.g. "" is resolved as an address during DistributionResult
this case is now covered. Hopefully, the test case will detect issues in the future

Identify issues during DistributionResult calls
